#!/usr/bin/env bash


DIR="$PWD/application/modules/$1"

echo "criando module $1 em $DIR"

if [ -d "$DIR" ]; then
  echo "Diretório"
  echo "$DIR"
  echo "Já existe. Remova antes de criar novamente."
  exit;
fi 

mkdir "$DIR"
mkdir "$DIR/models"
mkdir "$DIR/views"
mkdir "$DIR/widgets"

touch "$DIR/controller.php"
touch "$DIR/views/index.php"
touch "$DIR/widgets/index.wid"

printstr="<?php\n\nclass ${1^} extends Controller\n{\n\n	public function index( array \$data = null )\n    {\n\n    \$indexView = \$this->loadView('$1.index', \$data);\n\n    }\n\n\n}"
echo -e $printstr >> "$DIR/controller.php"


printstr="<?php\n\nclass Index extends View\n{\n\n	public function render()\n	{\n\n	\$this->loadTemplateComponent('header');\n	\$this->loadWidget('$1.index');\n	\$this->loadTemplateComponent('footer');\n\n    }\n\n\n}";
echo -e $printstr >> "$DIR/views/index.php"

printstr="<?php\necho '$1 - index';"
echo -e $printstr >> "$DIR/widgets/index.wid"


